name: hisp 
version: '1.0.0'
synopsis: Lisp REPL interpreter
description: Please see the README.md for more information
category: Development
license: WTFPL
author: Otávio Pace
maintainer: otaviopp8@gmail.com
github: otaviopace/hisp
homepage: https://github.com/otaviopace/hisp#readme

dependencies:
  - base >= 4.7 && < 5
  - containers

executables:
  hisp-exe:
    main:                Main.hs
    source-dirs:
      - app
      - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  hisp-test:
    main:                Spec.hs
    source-dirs:
      - test/integration
      - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - QuickCheck
