version: 2

jobs:
  build:
    docker:
      - image: haskell
    steps:
      - checkout
      - run:
          name: Stack Setup
          command: stack setup
      - run:
          name: Stack Build
          command: stack build

  test:
    docker:
      - image: haskell
    steps:
      - checkout
      - run:
          name: Stack Setup
          command: stack setup
      - run:
          name: Stack Test
          command: stack test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
